config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :appointments, :dependent => :delete_all
	has_many :products, through: :appointments, :dependent => :delete_all
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :appointments, :dependent => :delete_all
	has_many :categories, through: :appointments, :dependent => :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@product=Product.all
	end

	def new
		@product=Product.new
	end

	def product_params
		params.require(:product).permit(:name, :price)
	end

	def create
		product=Product.new(product_params)
		if product.save
			if params[:perfumes]=="1" 
				Category.find(1).products<<product
			end
			if params[:libros]=="1" 
				Category.find(2).products<<product
			end
			if params[:tecnologia]=="1" 
				Category.find(3).products<<product
			end
			if params[:electrodomesticos]=="1" 
				Category.find(4).products<<product
			end
			if params[:aseo]=="1" 
				Category.find(5).products<<product
			end
			if params[:juguetes]=="1" 
				Category.find(6).products<<product
			end
			if params[:ropa]=="1" 
				Category.find(7).products<<product
			end
			if params[:oficina]=="1" 
				Category.find(8).products<<product
			end
			if params[:mascota]=="1" 
				Category.find(9).products<<product
			end
			redirect_to products_path
		else
			render :new
		end
	end

	def edit
		@product=Product.find(params[:id])
	end

	def update
		product=Product.find(params[:id])

		Category.find(1).products.delete(product)
		Category.find(2).products.delete(product)
		Category.find(3).products.delete(product)
		Category.find(4).products.delete(product)
		Category.find(5).products.delete(product)
		Category.find(6).products.delete(product)
		Category.find(7).products.delete(product)
		Category.find(8).products.delete(product)
		Category.find(9).products.delete(product)
		product.categories=[]


		if product.update(product_params)
			if params[:perfumes]=="1" || params[:perfumes]=="yes"
				Category.find(1).products<<product
			end
			if params[:libros]=="1" || params[:libros]=="yes"
				Category.find(2).products<<product
			end
			if params[:tecnologia]=="1" || params[:tecnologia]=="yes"
				Category.find(3).products<<product
			end
			if params[:electrodomesticos]=="1" || params[:electrodomesticos]=="yes" 
				Category.find(4).products<<product
			end
			if params[:aseo]=="1" || params[:aseo]=="yes"
				Category.find(5).products<<product
			end
			if params[:juguetes]=="1" || params[:juguetes]=="yes"
				Category.find(6).products<<product
			end
			if params[:ropa]=="1" || params[:ropa]=="yes" 
				Category.find(7).products<<product
			end
			if params[:oficina]=="1" || params[:oficina]=="yes" 
				Category.find(8).products<<product
			end
			if params[:mascota]=="1" || params[:mascota]=="yes" 
				Category.find(9).products<<product
			end
			redirect_to products_path
		else
			render :edit
		end
	end

	def destroy
	  product = Product.find(params[:id])
	  product.destroy

	  redirect_to products_path
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Productos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Editar Producto</h1>
<%= form_for @product do |f| %>
<div>
	<%= f.text_field :name, placeholder: "Nombre del producto" %>
</div>
<div>
	<%= f.text_field :price, placeholder: "Precio del producto" %>
</div>
<div>
	<% if @product.categories.include?(Category.find(1)) %>
	<%= check_box_tag (:perfumes), "1", true %>
	<% else %>
	<%= check_box_tag (:perfumes), "1" %>
	<% end %>
	<%= label_tag(:perfumes, "Perfumes") %>
</div>
<div>
	<% if @product.categories.include?(Category.find(2)) %>
	<%= check_box_tag (:libros), "2", true %>
	<% else %>
	<%= check_box_tag (:libros), "2" %>
	<% end %>
	<%= label_tag(:libros, "Libros") %>
</div>
<div>
	<% if @product.categories.include?(Category.find(3)) %>
	<%= check_box_tag (:tecnologia), "3", true %>
	<% else %>
	<%= check_box_tag (:tecnologia), "3" %>
	<% end %>
	<%= label_tag(:tecnologia, "Tecnología") %>
</div>
<div>
	<% if @product.categories.include?(Category.find(4)) %>
	<%= check_box_tag (:electrodomesticos), "4", true %>
	<% else %>
	<%= check_box_tag (:electrodomesticos), "4" %>
	<% end %>
	<%= label_tag(:electrodomesticos, "Electrodomésticos") %>
</div>
<div>
	<% if @product.categories.include?(Category.find(5)) %>
	<%= check_box_tag (:aseo), "5", true %>
	<% else %>
	<%= check_box_tag (:aseo), "5" %>
	<% end %>
	<%= label_tag(:aseo, "Aseo") %>
</div>
<div>
	<% if @product.categories.include?(Category.find(6)) %>
	<%= check_box_tag (:juguetes), "6", true %>
	<% else %>
	<%= check_box_tag (:juguetes), "6" %>
	<% end %>
	<%= label_tag(:juguetes, "Juguetes") %>
</div>
<div>
	<% if @product.categories.include?(Category.find(7)) %>
	<%= check_box_tag (:ropa), "7", true %>
	<% else %>
	<%= check_box_tag (:ropa), "7" %>
	<% end %>
	<%= label_tag(:ropa, "Ropa") %>
</div>
<div>
	<% if @product.categories.include?(Category.find(8)) %>
	<%= check_box_tag (:oficina), "8", true %>
	<% else %>
	<%= check_box_tag (:oficina), "8" %>
	<% end %>
	<%= label_tag(:oficina, "Oficina") %>
</div>
<div>
	<% if @product.categories.include?(Category.find(9)) %>
	<%= check_box_tag (:mascota), "9", true %>
	<% else %>
	<%= check_box_tag (:mascota), "9" %>
	<% end %>
	<%= label_tag(:mascota, "Mascotas") %>
</div>
<div>
	<%= f.submit "Publicar Producto" %>
</div>
<% end %> 

app/views/products/index.html.erb
<h1>Products</h1>
<%= link_to "Nuevo Producto", new_product_path %>
<table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Precio</th>
        <th>Categorías</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @product.each do |i| %>
      <tr>
        <td><%= i.name %></td>
        <td><%= i.price %></td>
        <td>
          <% i.categories.each do |j| %>
          <%= j.name %>
          <% end %>
        </td>
        <td>
          <a href="/products/<%= i.id %>/edit">Editar</a> 
          <a href="/products/<%= i.id %>" data-method="delete">eliminar</a>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/products/new.html.erb
<h1>Nuevo Producto</h1>
<%= form_for @product do |f| %>
<div>
	<%= f.text_field :name, placeholder: "Nombre del producto" %>
</div>
<div>
	<%= f.text_field :price, placeholder: "Precio del producto" %>
</div>
<div>
	<%= check_box_tag (:perfumes), "1" %>
	<%= label_tag(:perfumes, "Perfumes") %>
</div>
<div>
	<%= check_box_tag (:libros), "2" %>
	<%= label_tag(:libros, "Libros") %>
</div>
<div>
	<%= check_box_tag (:tecnologia), "3" %>
	<%= label_tag(:tecnologia, "Tecnología") %>
</div>
<div>
	<%= check_box_tag (:electrodomesticos), "4" %>
	<%= label_tag(:electrodomesticos, "Electrodomésticos") %>
</div>
<div>
	<%= check_box_tag (:aseo), "5" %>
	<%= label_tag(:aseo, "Aseo") %>
</div>
<div>
	<%= check_box_tag (:juguetes), "6" %>
	<%= label_tag(:juguetes, "Juguetes") %>
</div>
<div>
	<%= check_box_tag (:ropa), "7" %>
	<%= label_tag(:ropa, "Ropa") %>
</div>
<div>
	<%= check_box_tag (:oficina), "8" %>
	<%= label_tag(:oficina, "Oficina") %>
</div>
<div>
	<%= check_box_tag (:mascotas), "9" %>
	<%= label_tag(:mascotas, "Mascotas") %>
</div>
<div>
	<%= f.submit "Publicar Producto" %>
</div>
<% end %> 